#版本号 我的建议是不要自己改~
version: 1.0.0

#填 SX 或 AP
depend: "SX"

#是否启用mysql 为true则在database.yml中填写相关信息.
mysql: false

#不使用mysql时,使用sqlite文件的位置. 请填写绝对路径!
#如: "D:\\minecraft\\Server1.12.2\\plugins\\XgpEquipmentSlot\\data.db"
#记得路径要打两个 -> '\'
#留空为默认位置。
sqlite: ""

#sqlite文件存储还是太慢了?  试试redis！
#是否使用redis缓存, 请在database.yml中详细配置.
redis: false

#是否检测新版本信息并提醒
#上个插件有人建议的= =
checkNewVersion: true

#是否禁用原版装备栏
#反正就是启用了这一项玩家穿上装备就会被扒下来，虽然我也不知道有什么用？ 也许你可以完全依赖本插件的装备栏！
disableRawEquipmentSlot: false

#默认装备栏name 即直接使用/xes openInv 就等同于/xes openInv default
defaultEquipmentSlot: "default"